# Generated by Django 5.0.6 on 2024-08-08 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Укажите дату создания",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
