# Generated by Django 5.0.6 on 2024-08-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blog_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                help_text="Укажите дату последнего изменения записи",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
