# Generated by Django 5.0.6 on 2024-07-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Укажите дату создания записи",
                null=True,
                verbose_name="Дата создания записи",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите цену за покупку",
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                help_text="Укажите дату последнего изменения записи",
                null=True,
                verbose_name="Дата последнего изменения записи",
            ),
        ),
    ]
