# Generated by Django 5.0.6 on 2024-08-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_image_product_photo_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание продукта",
                max_length=500,
                null=True,
                verbose_name="Описание продукта",
            ),
        ),
    ]
